### ISSUE TITLE
TypeError: code() takes at least 14 arguments (13 given)

### ISSUE THREAD

**Issue by bbkali** [yeshan333/blogtest#2]
<img width="1241" alt="image" src="https://user-images.githubusercontent.com/25882066/153441018-122145a4-425d-4636-9e3e-a5ccb97b9b7f.png">

**Comment by yeshan333** [comment]
> <img alt="image" width="1241" src="https://user-images.githubusercontent.com/25882066/153441018-122145a4-425d-4636-9e3e-a5ccb97b9b7f.png">

what is your flask version？

**Comment by yeshan333** [comment]
> <img alt="image" width="1241" src="https://user-images.githubusercontent.com/25882066/153441018-122145a4-425d-4636-9e3e-a5ccb97b9b7f.png">

I updated the README. The correct Python and Flask versions should be used.

https://github.com/yeshan333/flask_blog#quick-start

**Comment by bbkali** [comment]
Thank you for your guidance. I have used version 3.6 and can run my blog normally. It's great!
